import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import ShinyText from '@/bits/TextAnimations/ShinyText/ShinyText'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} dark`} 
      >
        <body className="antialiased bg-white text-black dark:bg-[#0d0d0d] dark:text-white transition-colors duration-300">
          <header className="flex justify-end items-center px-4 py-2 gap-4 h-16 border-b border-gray-200 dark:border-gray-800 shadow-sm">
            <SignedOut>
              <SignInButton>
                <button className="text-sm sm:text-base px-4 py-2 rounded-full font-medium bg-transparent border border-[#6c47ff] text-[#6c47ff] hover:bg-[#6c47ff] hover:text-white transition">
                  Sign In
                </button>
              </SignInButton>

              <SignUpButton>
                <button className="text-sm sm:text-base px-4 py-2 rounded-full font-medium bg-[#6c47ff] text-white hover:bg-black hover:text-[#6c47ff] transition">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>

            <SignedIn>
<div className="absolute left-4 flex items-center gap-4 text-lg font-semibold">
  <ShinyText text="Bae" speed={3} />
</div>

<div className="flex items-center justify-end">
  <UserButton />
</div>

              
            </SignedIn>
          </header>

          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  )
}
